// ─────────────────────────────────────────────────────────────
// IndoPak 15-line mushaf service.
//
// Performance model (approved design — "both, lazy-loaded asset"):
//   • A tiny page↔surah↔juz index is ALWAYS available (derived from the
//     114-surah table) so New Lesson shows correct details with ZERO
//     startup cost.
//   • The heavy line-by-line Arabic text (assets/quran_indopak15_pages.json,
//     ~1.8 MB) is required LAZILY the first time a page's lines are opened,
//     then cached. It never runs at app launch.
//
// Drop the file generated by scripts/generate-mushaf.mjs into
// assets/quran_indopak15_pages.json and the exact IndoPak page/line data
// automatically takes over from the fallback index.
// ─────────────────────────────────────────────────────────────
import { ALL_SURAHS } from './surahs';

export const MUSHAF_PAGES = 604;
export const LINES_PER_PAGE = 15;

export type MushafLineType = 'ayah' | 'surah_header_or_basmalah';

export interface MushafLine {
  line: number;
  type: MushafLineType;
  text: string;
  surah?: number;
}

export interface MushafPage {
  page: number;
  verse_keys: string[];
  juz: number[];
  line_count: number;
  lines: MushafLine[];
}

export interface MushafFile {
  mushaf: { id: number; code: string; lines_per_page: number; script: string };
  source: string;
  pages: MushafPage[];
}

/** Compact per-page info used by the entry screen. */
export interface PageInfo {
  page: number;
  surahIds: number[];
  juz: number[];
  firstVerse?: string;
  lastVerse?: string;
  lineCount: number;
  fromFile: boolean; // true when derived from the real IndoPak file
}

// ── Lazy state ───────────────────────────────────────────────
let _file: MushafFile | null = null;
let _fileTried = false;
let _pageMap: Map<number, MushafPage> | null = null;

/** Lazily require the heavy asset. Returns null if it isn't present/empty. */
function loadFile(): MushafFile | null {
  if (_fileTried) return _file;
  _fileTried = true;
  const tryLoad = (data: any): boolean => {
    if (data && Array.isArray(data.pages) && data.pages.length > 0) {
      _file = data as MushafFile;
      _pageMap = new Map((data.pages as MushafPage[]).map(p => [p.page, p]));
      return true;
    }
    return false;
  };
  try {
    // IndoPak only. The Teacher app also probed for a second (Uthmani) asset
    // first; this app ships one script, and a static require of a file that
    // isn't in the bundle is a Metro build error, not a catchable runtime one.
    // The require stays lazy so the ~1.8 MB JSON never parses at startup.
    const loader = typeof require !== 'undefined' ? require : null;
    if (loader) tryLoad(loader('../../assets/quran_indopak15_pages.json'));
  } catch {
    _file = null; // asset missing → fall back silently
  }
  return _file;
}

// ── Fallback page→surah/juz index (from the 114-surah table) ──
// Approximate but consistent, so the wheels never show mismatched data
// before the exact IndoPak file is added.
interface SurahSpan { id: number; pageStart: number; pageEnd: number; juz: number }
let _spans: SurahSpan[] | null = null;

function surahSpans(): SurahSpan[] {
  if (_spans) return _spans;
  const sorted = [...ALL_SURAHS].sort((a, b) => a.id - b.id);
  _spans = sorted.map((s, i) => {
    const next = sorted[i + 1];
    const pageEnd = next ? Math.max(s.page_start, next.page_start) : MUSHAF_PAGES;
    return { id: s.id, pageStart: s.page_start, pageEnd, juz: s.juz_start };
  });
  return _spans;
}

/** Surah id(s) that appear on a given page (fallback estimate). */
function surahIdsOnPage(page: number): number[] {
  const ids = surahSpans()
    .filter(sp => page >= sp.pageStart && page <= sp.pageEnd)
    .map(sp => sp.id);
  if (ids.length) return ids;
  // Nearest preceding surah if nothing matched.
  const prev = [...surahSpans()].reverse().find(sp => sp.pageStart <= page);
  return prev ? [prev.id] : [1];
}

/** Rough juz for a page via the containing surah's starting juz. */
function juzOnPage(page: number): number[] {
  const ids = surahIdsOnPage(page);
  const juzSet = new Set<number>();
  for (const id of ids) {
    const s = ALL_SURAHS.find(x => x.id === id);
    if (s) juzSet.add(s.juz_start);
  }
  return juzSet.size ? Array.from(juzSet).sort((a, b) => a - b) : [1];
}

// ── Public API ───────────────────────────────────────────────

/** Full page (with line text). Loads the heavy file lazily. */
export function getMushafPage(page: number): MushafPage | null {
  loadFile();
  return _pageMap?.get(page) ?? null;
}

/** Lines for a page, or [] if the real file isn't installed. */
export function getPageLines(page: number): MushafLine[] {
  return getMushafPage(page)?.lines ?? [];
}

/**
 * Compact info for a page — prefers the exact IndoPak file, otherwise a
 * consistent fallback. Always returns something (never null) for 1..604.
 */
export function getPageInfo(page: number): PageInfo {
  const clamped = Math.min(Math.max(page, 1), MUSHAF_PAGES);
  const filePage = getMushafPage(clamped);
  if (filePage) {
    const surahIds = Array.from(
      new Set(filePage.verse_keys.map(k => parseInt(k.split(':')[0], 10)))
    ).filter(Boolean);
    return {
      page: clamped,
      surahIds: surahIds.length ? surahIds : surahIdsOnPage(clamped),
      juz: filePage.juz?.length ? filePage.juz : juzOnPage(clamped),
      firstVerse: filePage.verse_keys[0],
      lastVerse: filePage.verse_keys[filePage.verse_keys.length - 1],
      lineCount: filePage.line_count || LINES_PER_PAGE,
      fromFile: true,
    };
  }
  return {
    page: clamped,
    surahIds: surahIdsOnPage(clamped),
    juz: juzOnPage(clamped),
    lineCount: LINES_PER_PAGE,
    fromFile: false,
  };
}

/** The page a surah starts on (for syncing the page wheel to a surah pick). */
export function pageForSurah(surahId: number): number {
  return ALL_SURAHS.find(s => s.id === surahId)?.page_start ?? 1;
}

// ── Real juz → page mapping (juz sizes vary; juz 1, 29, 30 are 20+ pages) ────
let _juzBounds: { from: number; to: number }[] | null = null;
function computeJuzBounds(): { from: number; to: number }[] {
  const bounds: { from: number; to: number }[] = Array.from({ length: 30 }, () => ({ from: 0, to: 0 }));
  loadFile();
  if (_pageMap) {
    // Walk every page, record the min/max page for each juz it belongs to.
    for (let p = 1; p <= MUSHAF_PAGES; p++) {
      const info = getPageInfo(p);
      for (const j of info.juz) {
        if (j >= 1 && j <= 30) {
          const b = bounds[j - 1];
          if (b.from === 0 || p < b.from) b.from = p;
          if (p > b.to) b.to = p;
        }
      }
    }
  }
  // Fallback for any juz with no data: even 20.13-page split.
  for (let j = 1; j <= 30; j++) {
    const b = bounds[j - 1];
    if (b.from === 0) {
      b.from = Math.round((j - 1) * 20.13) + 1;
      b.to = j === 30 ? 604 : Math.round(j * 20.13);
    }
  }
  return bounds;
}

/** First/last mushaf page of a juz (1–30), from the real file when available. */
export function juzPageBounds(juz: number): { from: number; to: number } {
  if (!_juzBounds) _juzBounds = computeJuzBounds();
  const j = Math.min(Math.max(juz, 1), 30);
  return _juzBounds[j - 1];
}

/** Number of mushaf pages in a juz (varies: ~20, but 20+ for juz 1, 29, 30). */
export function juzPageCount(juz: number): number {
  const b = juzPageBounds(juz);
  return b.to - b.from + 1;
}

/** Convert an absolute mushaf page to its page-number WITHIN its juz (1-based). */
export function pageWithinJuz(juz: number, absolutePage: number): number {
  const b = juzPageBounds(juz);
  return Math.min(Math.max(absolutePage - b.from + 1, 1), b.to - b.from + 1);
}

/** Convert a within-juz page number back to the absolute mushaf page. */
export function juzPageToAbsolute(juz: number, withinPage: number): number {
  const b = juzPageBounds(juz);
  return Math.min(b.from + withinPage - 1, b.to);
}

/** Whether the real IndoPak text file is installed. */
export function hasMushafFile(): boolean {
  loadFile();
  return _file != null;
}

/** Arabic-Indic page label (e.g. ٤٤ for 44). */
export function toArabicNumber(n: number): string {
  const digits = '٠١٢٣٤٥٦٧٨٩';
  return String(n).replace(/[0-9]/g, (d) => digits[Number(d)]);
}

/** Surah id whose banner/basmalah sits on a given line (if any). */
export function bannerSurahForLine(page: number, line: number): number | undefined {
  return getMushafPage(page)?.lines.find(l => l.line === line)?.surah;
}

// Traditional Arabic names of the 30 juz (by their opening words).
const JUZ_NAMES_AR = [
  'الٓمٓ', 'سَيَقُولُ', 'تِلۡكَ الرُّسُلُ', 'لَنۡ تَنَالُوا', 'وَالۡمُحۡصَنَاتُ',
  'لَا يُحِبُّ اللّٰهُ', 'وَإِذَا سَمِعُوا', 'وَلَوۡ أَنَّنَا', 'قَالَ الۡمَلَأُ', 'وَاعۡلَمُوٓا',
  'يَعۡتَذِرُونَ', 'وَمَا مِنۡ دَابَّةٍ', 'وَمَآ أُبَرِّئُ', 'رُبَمَا', 'سُبۡحَانَ الَّذِيٓ',
  'قَالَ أَلَمۡ', 'اقۡتَرَبَ لِلنَّاسِ', 'قَدۡ أَفۡلَحَ', 'وَقَالَ الَّذِينَ', 'أَمَّنۡ خَلَقَ',
  'اُتۡلُ مَآ أُوحِيَ', 'وَمَنۡ يَّقۡنُتۡ', 'وَمَا لِيَ', 'فَمَنۡ أَظۡلَمُ', 'إِلَيۡهِ يُرَدُّ',
  'حٰمٓ', 'قَالَ فَمَا خَطۡبُكُمۡ', 'قَدۡ سَمِعَ اللّٰهُ', 'تَبَارَكَ الَّذِي', 'عَمَّ',
];

/** Traditional Arabic name of a juz (1–30), e.g. 1 → "الٓمٓ". */
export function juzNameAr(juz: number): string {
  return JUZ_NAMES_AR[juz - 1] ?? '';
}

// ── Ayah-level segmentation ──────────────────────────────────
// A student always stops at the END OF AN AYAH, never mid-line. So the reader
// selects whole ayahs. We split each page into ayah units, tracking which
// line(s) each ayah spans and the exact line where it ends.

const AR_NUM_TOKEN = /^[\u0660-\u0669\u06F0-\u06F9]+$/;

export interface AyahSegment { line: number; text: string }
export interface PageAyah {
  index: number;        // position within the page (0-based)
  key: string;          // "2:6"
  surah: number;
  ayah: number;
  startLine: number;    // first line this ayah appears on
  endLine: number;      // line where the ayah number sits (where it ends)
  complete: boolean;    // false if it continues onto the next page
  segments: AyahSegment[]; // per-line text pieces (words joined)
}

export interface LineSegment { ayahIndex: number; text: string }

export interface PageAyahs {
  page: number;
  ayahs: PageAyah[];
  /** Per line number → ordered ayah text segments (for rendering). */
  lineSegments: Map<number, LineSegment[]>;
}

const _ayahCache = new Map<number, PageAyahs | null>();

/**
 * Break a page into ayah units. Words are assigned to the current ayah until an
 * ayah-number token is reached (which closes that ayah); the number stays with
 * its ayah so the ۝ ornament renders in place.
 */
export function getPageAyahs(page: number): PageAyahs | null {
  if (_ayahCache.has(page)) return _ayahCache.get(page)!;
  const mp = getMushafPage(page);
  if (!mp) { _ayahCache.set(page, null); return null; }

  const keys = mp.verse_keys;
  const ayahs: PageAyah[] = [];
  const lineSegments = new Map<number, LineSegment[]>();
  let ptr = 0;

  const ensure = (i: number): PageAyah => {
    if (!ayahs[i]) {
      const key = keys[Math.min(i, keys.length - 1)] ?? '';
      const [s, a] = key.split(':').map(Number);
      ayahs[i] = {
        index: i, key, surah: s || 0, ayah: a || 0,
        startLine: 0, endLine: 0, complete: false, segments: [],
      };
    }
    return ayahs[i];
  };

  const pushSeg = (i: number, line: number, text: string) => {
    if (!text.trim()) return;
    const ay = ensure(i);
    if (!ay.startLine) ay.startLine = line;
    ay.endLine = line;
    ay.segments.push({ line, text });
    const arr = lineSegments.get(line) ?? [];
    arr.push({ ayahIndex: i, text });
    lineSegments.set(line, arr);
  };

  for (const ln of mp.lines) {
    if (ln.type !== 'ayah') continue;
    const words = ln.text.replace(/\u200f/g, '').trim().split(/\s+/).filter(Boolean);
    let chunk: string[] = [];
    for (const w of words) {
      if (AR_NUM_TOKEN.test(w)) {
        chunk.push(w);
        pushSeg(ptr, ln.line, chunk.join(' '));
        ensure(ptr).complete = true;
        ptr++;
        chunk = [];
      } else {
        chunk.push(w);
      }
    }
    if (chunk.length) pushSeg(ptr, ln.line, chunk.join(' '));
  }

  const result: PageAyahs = { page, ayahs: ayahs.filter(Boolean), lineSegments };
  _ayahCache.set(page, result);
  return result;
}



